from __future__ import annotations

import re


def apply_curated_corrections(text: str) -> str:
    """Apply user-verified corrections to known source text defects."""
    text = apply_clean_teaching_doc_corrections(text)
    text = text.replace(
        "महायज्ञः Mahayajña\nThe great sacrificer.\n\nमहांश्चासौ यज्वश्चेति लोकसङ्ग्रहार्थं यज्ञान् निर्वर्तवन् महायज्ञः ।",
        "महायज्वा Mahāyajvā\nThe great sacrificer.\n\nमहांश्चासौ यज्वश्चेति लोकसङ्ग्रहार्थं यज्ञान् निर्वर्तवन् महायज्वा ।",
        1,
    )
    text = text.replace(
        "Thus, He is Mahayajña,\nthe great sacrificer.",
        "Thus, He is Mahāyajvā,\nthe great sacrificer.",
        1,
    )
    text = text.replace(
        "lokasaṅgraha, the good of the world and hence, He is\nMahayajña.\n\nमहायज्ञः Mahayajña",
        "lokasaṅgraha, the good of the world and hence, He is\nMahāyajvā.\n\nमहायज्ञः Mahayajña",
        1,
    )
    text = text.replace(
        "HATTA: Kṛtagamaḥ (655)\nThe author of the Vedas.",
        "कृतागमः Kṛtagamaḥ (655)\nThe author of the Vedas.",
        1,
    )
    text = text.replace(
        "अनन्त: Anantaḥ (886)\nThe limitless.",
        "अनन्तः Anantaḥ (886)\nThe limitless.",
        1,
    )
    text = text.replace(
        "Dhananjayaḥ Dhananjayah\nThe conqueror of wealth.",
        "धनञ्जयः Dhananjayah\nThe conqueror of wealth.",
        1,
    )
    text = text.replace(
        "WY: Prabhuḥ (299)\nThe one who has unsurpassed skill.",
        "प्रभुः Prabhuḥ (299)\nThe one who has unsurpassed skill.",
        1,
    )
    text = text.replace(
        "Ajah Ajah (204, 521)\nThe unborn.",
        "अजः Ajah (204, 521)\nThe unborn.",
        1,
    )
    text = text.replace(
        "Aja: Sarveśvaraḥ\nThe Lord of all.",
        "सर्वेश्वरः Sarveśvaraḥ\nThe Lord of all.",
        1,
    )
    text = text.replace(
        "Ajaḥ (95, 521)\n-The one who moves.",
        "अजः Ajaḥ (95, 521)\nThe one who moves.",
        1,
    )
    text = text.replace(
        "HAM: Anala (711)\nThe one who is never satiated.",
        "अनलः Anala (711)\nThe one who is never satiated.",
        1,
    )
    text = text.replace(
        "Kāmaha: Kāmaha\nThe destroyer of desires.",
        "कामहा Kāmaha\nThe destroyer of desires.",
        1,
    )
    text = text.replace(
        "Yadḥ Suvrataḥ (818)\nThe one with an admirable commitment.",
        "सुव्रतः Suvrataḥ (818)\nThe one with an admirable commitment.",
        1,
    )
    text = text.replace(
        "सु, शोभनं व्रतमस्येति Yadḥ |",
        "सु, शोभनं व्रतमस्येति सुव्रतः |",
        1,
    )
    text = text.replace(
        "Ajaḥ Ajah (95, 204)\nThe one in the form of Manmatha.",
        "अजः Ajah (95, 204)\nThe one in the form of Manmatha.",
        1,
    )
    text = text.replace(
        "Mahārhaḥ Maharhaḥ\nThe one who deserves worship.",
        "महार्हः Maharhaḥ\nThe one who deserves worship.",
        1,
    )
    text = text.replace(
        "HAG: Analaḥ (293)\nThe one who has no limit.",
        "अनलः Analaḥ (293)\nThe one who has no limit.",
        1,
    )
    text = text.replace(
        "Ad: Suvrataḥ (455)\nThe one who accepts all the offerings.",
        "सुव्रतः Suvrataḥ (455)\nThe one who accepts all the offerings.",
        1,
    )
    text = text.replace(
        "AST Srasta (588)\nThe creator of all.",
        "स्रष्टा Srasta (588)\nThe creator of all.",
        1,
    )
    text = text.replace(
        "अनिदेश्यवपुः Anirdesyavapuh (656)",
        "अनिर्देश्यवपुः Anirdesyavapuh (656)",
        1,
    )
    text = text.replace(
        "तत् अनिदेश्यं\nवपुरस्येति अनिर्देश्यवपु:।",
        "तत् अनिर्देश्यं\nवपुरस्येति अनिर्देश्यवपु:।",
        1,
    )
    text = text.replace(
        "अनिदेश्यवपुविष्णुवीरोऽ नन्तो धनञ्जयः ।। ७० ।।",
        "अनिर्देश्यवपुविष्णुवीरोऽ नन्तो धनञ्जयः ।। ७० ।।",
        1,
    )
    text = text.replace(
        "तदेव रूपमस्येति\nअनिदेश्यवपुः।",
        "तदेव रूपमस्येति\nअनिर्देश्यवपुः।",
        1,
    )
    text = text.replace(
        "सुवर्णबिन्दुरक्षोभ्यः सर्ववागीश्चरेश्वरः।\n\n"
        "महाहदो Herta महाभूतो महानिधिः।। ८६।।\n"
        "mahāhardo mahāgarbho mahābhūto mahānidhiḥ । । 86\n\n"
        "suvarnabinduraksobhyah sarvavagisvaresvarah |\n"
        "mahāhardo mahāgarbho mahābhūto mahānidhiḥ । । 86",
        "सुवर्णबिन्दुरक्षोभ्यः सर्ववागीश्वरेश्वरः।\n"
        "महाह्रदो महागर्तो महाभूतो महानिधिः।। ८६।।\n\n"
        "suvarnabinduraksobhyah sarvavagisvaresvarah |\n"
        "mahāhrado mahāgarto mahābhūto mahānidhiḥ || 86",
        1,
    )
    text = text.replace(
        "सर्ववागीश्वरोत्තරः Sarvavagisveśvarah\nThe Lord of all the lords of speech.",
        "सर्ववागीश्वरेश्वरः Sarvavagisveśvarah\nThe Lord of all the lords of speech.",
        1,
    )
    text = text.replace(
        "सर्वाणां वागीश्वराणां ब्रह्मादीनांपि ईश्वर: सर्ववागीश्वरोत्තරः।",
        "सर्वाणां वागीश्वराणां ब्रह्मादीनांपि ईश्वर: सर्ववागीश्वरेश्वरः।",
        1,
    )
    text = text.replace(
        "Hert: Mahāgartaḥ\nThe one who is like a great canyon.",
        "महागर्तः Mahāgartaḥ\nThe one who is like a great canyon.",
        1,
    )
    text = text.replace(
        "महागर्तवद् अस्य माया महती दुरत्यया इति Hert: |",
        "महागर्तवद् अस्य माया महती दुरत्यया इति महागर्तः |",
        1,
    )
    text = text.replace(
        "Held: Mahābhūtaḥ\nThe great being.",
        "महाभूतः Mahābhūtaḥ\nThe great being.",
        1,
    )
    text = text.replace(
        "महांश्चासौ निधिश्च इति महानिdeoः।",
        "महांश्चासौ निधिश्च इति महानिधिः।",
        1,
    )
    text = text.replace(
        "अनादिनिधनो धाता विधाता धातुरुत्paramः।। ५ ।।",
        "अनादिनिधनो धाता विधाता धातुरुत्तमः।। ५ ।।",
        1,
    )
    text = text.replace(
        "वेधाः स्वाङ्गोऽजितः कृष्णो दृढः सङ्कर्षणोऽचytah |",
        "वेधाः स्वाङ्गोऽजितः कृष्णो दृढः सङ्कर्षणोऽच्युतः |",
        1,
    )
    text = text.replace(
        "bhagavan bhagaha’ऽnandi vanamali halayudhah |",
        "bhagavan bhagaha’nandi vanamali halayudhah |",
        1,
    )
    text = text.replace(
        "आश्चaryaवच्चैनमन्यः शृणोति श्रुत्वाप्येनं वेद न चैव कश्चित्।। 5.2.29",
        "आश्चर्यवच्चैनमन्यः शृणोति श्रुत्वाप्येनं वेद न चैव कश्चित्।। 5.2.29",
        1,
    )
    text = text.replace(
        "सर्वप्रhinayudha ओं नम इति।।",
        "सर्वप्रहरणायुध ओं नम इति।।",
        1,
    )
    text = text.replace(
        "777. Durlabhaḥ\nदि\nुभ\nव ेः\nThe one who is not gained easily.",
        "777. Durlabhaḥ\nदुःखेन, (दुर्लभया भक्त्या) लभ्यत इति दुर्लभः।\nThe one who is not gained easily.",
        1,
    )
    text = text.replace(
        "धनुर्धरो धनुवदो दण्डो दमयिता दमः।\n\n"
        "अपराजितः सर्वसहो नियन्ताऽनियमोऽयमः।। ९२।।\n"
        "dhanurdharo dhanuvado daṇḍo damayitā damaḥ |\n"
        "aparajitah sarvasaho niyantā’niyamo’yamah | | 92",
        "धनुर्धरो धनुर्वेदो दण्डो दमयिता दमः।\n"
        "अपराजितः सर्वसहो नियन्ताऽनियमोऽयमः।। ९२।।\n\n"
        "dhanurdharo dhanurvedo daṇḍo damayitā damaḥ |\n"
        "aparajitah sarvasaho niyantā’niyamo’yamah || 92",
        1,
    )
    text = text.replace("योगं विदन्ति विचारयet, जानन्ति, उक्त इति वा योगविदः।", "योगं विदन्ति विचारयन्ति, जानन्ति, उक्त इति वा योगविदः।", 1)
    text = text.replace("शं सुखं भक्तानां (मङ्गलं मोce) भावयतीति शंभुः ।", "शं सुखं भक्तानां (मङ्गलं मोक्षं) भावयतीति शंभुः ।", 1)
    text = text.replace("मेधा - बहुग्रन्थ-धारण-सामarkyam, सा यस्यास्ति स मेधावी ।", "मेधा - बहुग्रन्थ-धारण-सामर्थ्यम्, सा यस्यास्ति स मेधावी ।", 1)
    text = text.replace("संसारचक्रम् आवर्तयितुं शक्Num अस्येति आवर्तनः।", "संसारचक्रम् आवर्तयितुं शक्तिः अस्येति आवर्तनः।", 1)
    text = text.replace("ओजस्तेजोद्यutidhar Ojastejodyutidharah", "ओजस्तेजोद्युतिधरः Ojastejodyutidharah", 1)
    text = text.replace("ज्ञानं उत्तमं प्रकृष्टमजन्यं अनवच्छिन्नं, सर्वस्य साधकतममिति ज्ञानमुत्thamं ब्रह्म।", "ज्ञानं उत्तमं प्रकृष्टमजन्यं अनवच्छिन्नं, सर्वस्य साधकतममिति ज्ञानमुत्तमं ब्रह्म।", 1)
    text = text.replace("कूटस्थः SARA |", "कूटस्थः अक्षरम् |", 1)
    text = text.replace("विश्वरूपत्वात्पुरुः, उत्कृष्टत्वात्सत्तमः। पुरुश्नासौ सत्तमश्चेति पुरुसत्lamः |", "विश्वरूपत्वात्पुरुः, उत्कृष्टत्वात्सत्तमः। पुरुश्नासौ सत्तमश्चेति पुरुसत्तमः |", 1)
    text = text.replace("सत्या सन्धा सङ्कल्पः अस्येति AAAS: |", "सत्या सन्धा सङ्कल्पः अस्येति सत्यसन्धः |", 1)
    text = text.replace("सर्वभूतेभ्यः समुद्रिक्तत्वात् उदीfnः।", "सर्वभूतेभ्यः समुद्रिक्तत्वात् उदीर्णः।", 1)
    text = text.replace("यमुनासम्बन्निना देवकीवसुदेव नन्द यशोदा बलबhadra सुभद्रादयः", "यमुनासम्बन्निना देवकीवसुदेव नन्द यशोदा बलभद्र सुभद्रादयः", 1)
    text = text.replace("तस्मात् TSES: |", "तस्मात् दुर्धरः |", 1)
    text = text.replace("इन्द्रस्य कर्मव कर्मास्येति इdtraकर्मा।", "इन्द्रस्य कर्मव कर्मास्येति इन्द्रकर्मा।", 1)
    text = text.replace("पर्jan़यवद् आध्यात्मिकादितापत्रयं शमयतीति", "पर्जन्यवद् आध्यात्मिकादितापत्रयं शमयतीति", 1)
    text = text.replace("आश्चर्यो वक्ता कुशलोऽस्य SAT आश्चर्यो ज्ञाता कुशलानुशिष्ट:", "आश्चर्यो वक्ता कुशलोऽस्य लब्धा आश्चर्यो ज्ञाता कुशलानुशिष्ट:", 1)
    text = text.replace("यज्ञगुphan |", "यज्ञगुह्यम् |", 1)
    text = text.replace(
        "अवितः Arcitaḥ\nThe one who is worshipped.",
        "अर्चितः Arcitaḥ\nThe one who is worshipped.",
        1,
    )
    text = text.replace(
        "सर्वदेवैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विद्यैर्विdyaiḥ…\n(Note: The OCR for the Sanskrit line is heavily corrupted; however, based on the context of “Arcita” and “worshipped by all”, the intended meaning is “worshipped by all devas/vidyas”.)",
        "सर्वदेवैर्विद्यैश्च अर्चित इति अर्चितः।",
        1,
    )
    text = re.sub(
        r"सर्वदेवैर्विद्यैर्विद्यै.*?\(Note: The OCR for the Sanskrit line is heavily corrupted; however, based on the context of “Arcita” and “worshipped by all”, the intended meaning is “worshipped by all devas/vidyas”.\)",
        "सर्वदेवैर्विद्यैश्च अर्चित इति अर्चितः।",
        text,
        count=1,
        flags=re.DOTALL,
    )
    text = text.replace("ĪśĪśvara-arpana", "Īśvara-arpana")
    text = text.replace("vara ārādhana", "Īśvara-ārādhana")
    text = text.replace(" sakta–committed", " āsakta–committed")
    text = text.replace(" m na,", " māna,")
    text = text.replace("lo as", "lokas")
    text = text.replace("askyoga", "as yoga")
    text = text.replace("pPParamātmā", "Paramātmā")
    text = re.sub(r"\bP+Paramātmā\b", "Paramātmā", text)
    text = re.sub(r"(?<![A-Za-zāīūṛṝḷḹṅñṭḍṇśṣḥĀĪŪṚṜḶḸṄÑṬḌṆŚṢḤ])arma\b", "karma", text)
    text = re.sub(r"(?<![A-Za-zāīūṛṝḷḹṅñṭḍṇśṣḥĀĪŪṚṜḶḸṄÑṬḌṆŚṢḤ])armas\b", "karmas", text)
    text = re.sub(r"\bujya Swamiji\b", "Pujya Swamiji", text)
    return apply_clean_teaching_doc_corrections(text)


def apply_clean_teaching_doc_corrections(text: str) -> str:
    """Corrections for The-Teaching-of-Visnusahasranama-clean.docx extraction defects."""
    replacements = {
        "studentsliving": "students living",
        "becauseBrahman": "because Brahman",
        "The three lettered omk ra": "The three lettered oṃkāra",
        "the dyam brahma": "the ādyam brahma",
        "pranava alone tray,": "pranava alone trayī,",
        "the pran va always": "the pranava always",
        "all vibh tis": "all vibhūtis",
        "Lordkin the form": "Lord in the form",
        "inkmaking this": "in making this",
        "back -ground": "background",
        "experierinces": "experiences",
        "unlesskyou": "unless you",
        "routeskyou": "routes you",
        "arrives atka": "arrives at a",
        "atka time": "at a time",
        "prārabdha- arma": "prārabdha-karma",
        "pra rabdha-karma": "prārabdha-karma",
        "pāpa- arma": "pāpa-karma",
        "pāpa arma": "pāpa-karma",
        "karma- phala": "karma-phala",
        "arma-phala": "karma-phala",
        " ujya Swamiji": " Pujya Swamiji",
        "vara-arpana": "Īśvara-arpana",
        "vara ārādhana": "Īśvara-ārādhana",
        " sa alpa": " saṅkalpa",
        "Īśvara rpa": "Īśvara-kṛpā",
        "14 lo as": "14 lokas",
        "śa tis": "śaktis",
        "PPPParamātmā": "Paramātmā",
        "PParamātmā": "Paramātmā",
        "ac uiring": "acquiring",
        " t be ": " to be ",
        "ārya- araṇa-sa ghāta": "kārya-karaṇa-saṅghāta",
        "bali a ba ra": "bali ka bakra",
        "sacrificial lambkin Hindi": "sacrificial lamb in Hindi",
        "He is ratāpana": "He is Pratāpana",
        "He is admī": "He is Padmī",
        "ī ṣaṇe": "īkṣaṇe",
        "Lordkin": "Lord in",
        "howkit was": "how it was",
        "maange more’so": "maange more’ so",
        "Ofcourse": "Of course",
        "ofcourse": "of course",
        "inspite of": "in spite of",
        "atka distance": "at a distance",
        "atka situation": "at a situation",
        "atka certain": "at a certain",
        "atka joke": "at a joke",
        "putskyou": "puts you",
        "makeskyou": "makes you",
        "thiskyou": "this you",
        "MMuktānām": "Muktānām",
        "kkkartā": "kartā",
        "kkartā": "kartā",
        "Bhūta rt": "Bhūtakṛt",
        "Bhūtabāvanaḥ": "Bhūtabhāvanaḥ",
        "ūtātmā": "Pūtātmā",
        "aramātmā": "Paramātmā",
        "u tānām paramā gatiḥ": "Muktānām paramā gatiḥ",
        "Vaṣaṭ āraḥ": "Vaṣaṭkāraḥ",
        "Hṛṣī eśaḥ": "Hṛṣīkeśaḥ",
        "Hṛṣī a": "Hṛṣīka",
        "Hṛṣī eśa": "Hṛṣīkeśa",
        "admanābhaḥ": "Padmanābhaḥ",
        "Viśva armā": "Viśvakarmā",
        "Sā ṣī": "Sākṣī",
        "Kṣetraj aḥ": "Kṣetrajñaḥ",
        "radhānapuruṣeśvaraḥ": "Pradhānapuruṣeśvaraḥ",
        "Śr mān": "Śrīmān",
        "Puskaraksah": "Puṣkarākṣaḥ",
        "hātā (951)": "Dhātā (951)",
        "hāturuttamaḥ": "Dhāturuttamaḥ",
        " arayita": "kārayita",
        "ka arayita": "kārayita",
        " loc er": " locker",
        "Sab Bhagavan i ripa": "Sab Bhagavan ki kṛpa",
        "antah arana": "antaḥkaraṇa",
        " arma yogi": " karma yogi",
        "every arma": "every karma",
        "what ind of arma": "what kind of karma",
        "a arta": "akartā",
        "the arta": "the kartā",
        "you are the arta": "you are the kartā",
        "I am the artā": "I am the kartā",
        "no artṛtva": "no kartṛtva",
        "arta and": "kartā and",
        "arta,": "kartā,",
        "artā,": "kartā,",
        " artā": " kartā",
        " artās": " kartās",
        " arana": " karaṇa",
        " anga": " aṅga",
        " angas": " aṅgas",
        "li ened": "likened",
        "disli e": "dislike",
        "ma eover": "makeover",
        "noc off": "knock off",
        "mista es": "mistakes",
        "underta ings": "undertakings",
        "s y": "sky",
        " arātmā": "parātmā",
        "G tā": "Gītā",
        "G ta": "Gītā",
        "bha tyā": "bhaktyā",
        "ananya- bhakti": "ananya-bhakti",
        "Īśvara is urlabha": "Īśvara is durlabha",
        "To recognise him,": "To recognise Him,",
        "look s": "looks",
        "conse uences": "consequences",
        "I s vara": "Īśvara",
        "j ānī": "jñānī",
        "e ā-rupa": "eka-rupa",
        "e a- artṛ a": "eka-kartṛka",
        "e a arma": "eka karma",
        "root’a ṣ’": "root ‘akṣ’",
        "Puṣ arā ṣa": "Puṣkarākṣa",
        "pea s": "peaks",
        "vi āsa": "vikāsa",
        "uiet": "quiet",
        "e a evāgra ās t": "eka evāgra āsīt",
        "iñcana": "kiñcana",
        "urati rama": "Duratikrama",
        "waterskyou": "waters you",
        "askyou": "ask you",
        "putskyou": "puts you",
        "drawskyou": "draws you",
        "purifieskyou": "purifies you",
        "iskyou": "is you",
        "meanskyou": "means you",
        "connectskyou": "connects you",
        "Askyou": "As you",
        "powerskyou": "powers you",
        "Perhapskyears": "Perhaps years",
        "takeskyears": "takes years",
        "kkkeepskyou": "keeps you",
        "keepskyou": "keeps you",
        "blac hole": "black hole",
        "uic to anger": "quick to anger",
        "work s": "works",
        "o ay": "okay",
        "Soemtimes": "Sometimes",
        "all- pervasive": "all-pervasive",
        "exceeed": "exceed",
        "uic ly": "quickly",
        "uic\nly": "quickly",
        "mMMaybe": "Maybe",
        "mmmaybe": "Maybe",
        "mMaybe": "Maybe",
        "Atleast": "At least",
        "atleast": "at least",
        "needs to done": "needs to be done",
        "Brahmanand": "Brahman and",
        "upto": "up to",
        "iskyoga": "is yoga",
        "He is edhaja.The yajamāna": "He is Medhaja. The yajamāna",
        "He is edhaja.": "He is Medhaja.",
        "wellentrenched": "well-entrenched",
        "id n’t": "didn’t",
        "qqquietly": "quietly",
        "qqquiet": "quiet",
        "qqquieter": "quieter",
        "dddon’t": "don’t",
        "dddon't": "don't",
        "kkkkkarma": "karma",
        "kkkkarma": "karma",
        "kkkkarma": "karma",
        "kkkarma": "karma",
        "atttibute": "attribute",
        "PPPPūtātmā": "Pūtātmā",
        "Bhagav n": "Bhagavān",
        "Bhagav n.": "Bhagavān.",
        "Kr ṣṇa": "Kṛṣṇa",
        "Sri Kr": "Śrī Kṛ",
        "Śrī Kr": "Śrī Kṛ",
        "La ṣmī": "Lakṣmī",
        "vi va": "viśva",
        "Vi va": "Viśva",
        "vi vam": "viśvam",
        "Vi vam": "Viśvam",
        "Vi ati": "Viśati",
        "vi anti": "viśanti",
        "a kara": "Śaṅkara",
        "rutis": "śrutis",
        "smrtis": "smṛtis",
        "v cya": "vācya",
        "v caka": "vācaka",
        "s m nya": "sāmānya",
        "a ras": "aśūras",
        "r dhana": "ārādhana",
        "k rtana": "kīrtana",
        "sā ṣī": "sākṣī",
        "j āni": "jñāni",
        "j ānī": "jñānī",
        "j āna": "jñāna",
        "jij āsu": "jijñāsu",
        "Jij āsā": "Jijñāsā",
        "s ete": "śete",
        "tva s": "tvaś",
        "yajn a": "yajña",
        "shetrajn a": "kṣetrajña",
        "kṣetraj a": "kṣetrajña",
        "pPPPParamātmā": "Paramātmā",
        "viśvaand": "viśva and",
        "includeskyour": "includes your",
        "becomeskyour": "becomes your",
        "expresskyour": "express your",
        "blesskyourself": "bless yourself",
        "Iskyour": "Is your",
        "variouskyugas": "various yugas",
        "variouskyajñas": "various yajñas",
        "comaparison": "comparison",
        "charactersitcs": "characteristics",
        "kalmasa": "kalmaṣa",
        "ĪśĪśvara-arpana": "Īśvara-arpana",
        "ĪśĪśĪśvara-arpana": "Īśvara-arpana",
        "bhūta rt": "bhūtakṛt",
        "Bhūta rt": "Bhūtakṛt",
        "Bhūtāni aroti iti bhūta rt": "Bhūtāni karoti iti bhūtakṛt",
        "Bhūtāni ta rt": "Bhūtāni karoti",
        "evahūti": "Devahūti",
        "namask ra": "namaskāra",
        "ahims paramo dharmah": "ahiṃsā paramo dharmaḥ",
        "without causing any himsa": "without causing any hiṃsā",
        "aditeh a handitayah mahyah patih": "aditeḥ akhaṇḍitāyāḥ mahyāḥ patiḥ",
        "a handita aditi": "akhaṇḍita aditi",
        "andbhakti": "and bhakti",
        "mil maids": "milkmaids",
        "drink s": "drinks",
        "araśurāma": "Paraśurāma",
        "Balara ma": "Balarāma",
        "sna es": "snakes",
        "ma ingPātala": "making Pātāla",
        "Vasuki,Airavata": "Vasuki, Airavata",
        "atsya, Kūrma,Varāha, Narsimha": "Matsya, Kūrma, Varāha, Narasimha",
        "Narsimha": "Narasimha",
        "Kṛsṇa": "Kṛṣṇa",
        "continous": "continuous",
        "faceboo": "Facebook",
        "haneśvara": "Dhaneśvara",
        "see skit": "sees it",
        "nowingly": "knowingly",
        "Sa arṣana": "Saṅkarṣaṇa",
        "radyumna": "Pradyumna",
        "ualified": "qualified",
        "en uired": "enquired",
        " im brahma": " kim brahma",
        "Atma rpa": "Atma rūpa",
        "rayers and wishes": "Prayers and wishes",
        "uring His": "During His",
        "askyoga": "as yoga",
        "mindboggling": "mind-boggling",
        "rahlada": "Prahlāda",
        "Prahlada": "Prahlāda",
        "Hiranya āśipu": "Hiraṇyakaśipu",
        "Hiraṇya aśipu": "Hiraṇyakaśipu",
        "askyet": "as yet",
        "If one is a vive,": "If one is a viveki,",
        "If one is an avive,": "If one is an aviveki,",
        "Sage amadagni": "Sage Jamadagni",
        "clue and dome-shaped": "blue and dome-shaped",
        "li uids": "liquids",
        "lic ed": "licked",
        "coskya": "coṣya",
        " lky way": " Milky Way",
        "ŚrīRāma": "Śrī Rāma",
        "ŚrīKrṣṇa": "Śrī Kṛṣṇa",
        "mil y ocean": "milky ocean",
        "Rishi esh": "Rishikesh",
        "ma ingPātala": "making Pātāla",
        "Vimu tātma": "Vimuktātmā",
        "a vive,": "a viveki,",
        "raddh": "śraddhā",
        "karmak nda": "karmakāṇḍa",
        "Mah bh rata": "Mahābhārata",
        "bh van": "bhāvana",
        "avisnu": "aviṣṇu",
        "aśaratha": "Daśaratha",
        "Śr Rāma": "Śrī Rāma",
        "Guru urnima": "Guru Pūrṇimā",
        "śśrutis": "śrutis",
        "śśraddhāā": "śraddhā",
        "śśraddhā": "śraddhā",
        "an tim ns": "anītimāns",
        "bh gya-bhogy ni": "bhāgya-bhogyāni",
        "su ham dyati": "sukham dyati",
        "asu hada": "asukhada",
        "ck ed with jñāna śa tiḥ": "backed with jñāna śaktiḥ",
        "Iccha śa tiḥ": "Iccha śaktiḥ",
        "jñāna śa tiḥ": "jñāna śaktiḥ",
        "all- nowingness": "all-knowingness",
        "Blood iamond": "Blood Diamond",
        "asa ga": "asaṅga",
        "arames vara": "Parameśvara",
        "ṣetraj a-paramātma-aikya": "kṣetrajña-paramātma-aikya",
        "Faceboo": "Facebook",
        "any of us don’t have mastery": "Many of us don’t have mastery",
        "devotes. arigraha": "devotees. Parigraha",
        "guru’shows": "guru’ shows",
        " forml": " form",
        "tūla-avidyā": "sthūla-avidyā",
        "evdutta": "Devadutta",
        " rewinter": " pre-winter",
        "sat āra": "satkāra",
        "sapta rsis": "sapta ṛṣis",
        "satyasa alpa": "satyasaṅkalpa",
        "Siddhasa alpa": "Siddhasaṅkalpa",
        "dar e aage": "dar ke aage",
        "upala ṣaṇa": "upalakṣaṇa",
        "sā āra": "sākāra",
        "Isvara srsti": "Īśvara-sṛṣṭi",
        "jiva srstīi": "jīva-sṛṣṭi",
        "jiva srsti": "jīva-sṛṣṭi",
        "srstīi": "sṛṣṭi",
        "srsti": "sṛṣṭi",
        "akhila-sattva-mitra-bh ta": "akhila-sattva-mitra-bhūta",
        "asta-m na-m ya": "asta-māna-māyā",
        "V sudeva": "Vāsudeva",
        "karma ānda": "karma-kāṇḍa",
        "pāramārthi a": "pāramārthika",
        "svayam-pra āśa": "svayam-prakāśa",
        "vya ta": "vyakta",
        "agnaye ida na mama": "agnaye idam na mama",
        "rajāpati": "Prajāpati",
        "back ward": "backward",
        " lable to": " available to",
        "philosoper": "philosopher",
        "mathematician-\nphilosopher": "mathematician-philosopher",
        "Cause For One’S Self-Disapproval": "Cause for One’s Self-Disapproval",
        "self- consciousness": "self-consciousness",
        "self-\nconsciousness": "self-consciousness",
        "self- judgement": "self-judgement",
        "self-\njudgement": "self-judgement",
        "self loath": "self-loathing",
        "knowledge- wise": "knowledge-wise",
        "knowledge-\nwise": "knowledge-wise",
        "get along  these assumptions": "get along with these assumptions",
        "get along with these assumptions": "get along with these assumptions",
        "devotes.\narigraha": "devotees.\nParigraha",
        "devotes. arigraha": "devotees. Parigraha",
        "hance he is called": "hence He is called",
        "PPrahlāda": "Prahlāda",
        "DDevadutta": "Devadutta",
        "dDevadutta": "Devadutta",
        "Agni,the": "Agni, the",
        "Ya śa": "Yakṣa",
        "puṇyaśravaṇa rtana": "puṇyaśravaṇa-kīrtana",
        " rtana, singing": " kīrtana, singing",
        " rtana. Īśvara": " kīrtana. Īśvara",
        " and rtana of Īśvara": " and kīrtana of Īśvara",
        " rtana of Īśvara": " kīrtana of Īśvara",
        "K rtana is": "Kīrtana is",
        "guṇa- īrtana": "guṇa-kīrtana",
        "Vāsudevaas": "Vāsudeva as",
        "isVāsudeva": "is Vāsudeva",
        "thekṣetra": "the kṣetra",
        "ŚriKṛṣṇa": "Śrī Kṛṣṇa",
        "bhogtā-the": "bhogtā, the",
        "bho tā, experiencer": "bhoktā, experiencer",
        "everthing": "everything",
        "āma, rodha": "kāma, krodha",
        " all- knowing": " all-knowing",
        "all- knowing": "all-knowing",
        "all- nowingness": "all-knowingness",
        "Prasad": "prasāda",
        "multi faceted": "multi-faceted",
        "multi colored": "multi-colored",
        "multi tasking": "multitasking",
        "this ind of spirituality": "this kind of spirituality",
        "This ind of a special manifestation is known amśa-avatāra.": "This kind of special manifestation is known as amśa-avatāra.",
        "the urāṇas": "the Purāṇas",
        "The urāṇas": "The Purāṇas",
        "Godess": "Goddess",
        "Viṣִִṇupurāִṇa": "Viṣṇupurāṇa",
        "‘ now Vyāsa": "‘Know Vyāsa",
        "Puṇḍar ā ṣa": "Puṇḍarīkākṣa",
        "Vyāsa ‘s": "Vyāsa’s",
        "sage Parashara": "sage Parāśara",
        "re establish": "re-establish",
        "aṣṭā ṣara-mantra": "aṣṭākṣara-mantra",
        "Spaṣṭa-a ṣara": "Spaṣṭākṣara",
        "Spaṣṭā ṣara": "Spaṣṭākṣara",
        "spaṣṭa-a ṣara": "spaṣṭākṣara",
        "spaṣṭā ṣara": "spaṣṭākṣara",
        "does not now,": "does not know,",
        "If he does not now,": "If he does not know,",
        "ākāṣa": "ākāśa",
        "Nārāyana": "Nārāyaṇa",
        "Śa ara": "Śaṅkara",
        "Śa ara uotes": "Śaṅkara quotes",
        "|| ॐ नमो नािायणाय ||": "|| ॐ नमो नारायणाय ||",
        "नािायण": "नारायण",
        "कृ ष्णेः": "कृष्णः",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)

    regex_replacements = [
        (r"\bma e\b", "make"),
        (r"\bma es\b", "makes"),
        (r"\bta e\b", "take"),
        (r"\bta es\b", "takes"),
        (r"\bli e\b", "like"),
        (r"\beeps\b", "keeps"),
        (r"\baybe\b", "Maybe"),
        (r"\beep\b", "keep"),
        (r"\bq+qualities\b", "qualities"),
        (r"\bq+quality\b", "quality"),
        (r"\bq+quite\b", "quite"),
        (r"\bualities\b", "qualities"),
        (r"\buality\b", "quality"),
        (r"\buite\b", "quite"),
        (r"\bindividqquality\b", "individuality"),
        (r"\bdqquality\b", "duality"),
        (r"\bnondqquality\b", "nonduality"),
        (r"\beqqquality\b", "equality"),
        (r"\bspiritqquality\b", "spirituality"),
        (r"\beeping\b", "keeping"),
        (r"\billed\b", "killed"),
        (r"\bill\b", "kill"),
        (r"\binds\b", "kinds"),
        (r"\bWhat ind of\b", "What kind of"),
        (r"\bwhat ind of\b", "what kind of"),
        (r"\boes\b", "Does"),
        (r"\bust ask you give\b", "Just as you give"),
        (r"\bust\b", "Just"),
        (r"\bost\b", "Most"),
        (r"\b[Tt]hin about it\b", "Think about it"),
        (r"\bthin it\b", "think it"),
        (r"\bspeaksomething\b", "speak something"),
        (r"\bspea\s+s\b", "speaks"),
        (r"\bspea\b", "speak"),
        (r"\bwho now their\b", "who know their"),
        (r"\bedha means a sacrifice\b", "Medha means a sacrifice"),
        (r"\bunderta\s+es\b", "undertakes"),
        (r"\bd\s+sā\b", "dīkṣā"),
        (r"\batka\s+time\b", "at a time"),
        (r"\batka\s+particular\b", "at a particular"),
        (r"\batka\s+speed\b", "at a speed"),
        (r"\batka\s+loss\b", "at a loss"),
        (r"\batka\s+physician\b", "at a physician"),
        (r"\batka\s+larger\b", "at a larger"),
        (r"\batka\s+certain\b", "at a certain"),
        (r"\bthinkk+ing\b", "thinking"),
        (r"\bthinkk+\b", "think"),
        (r"\bq+quarters\b", "quarters"),
        (r"\bq+quarter\b", "quarter"),
        (r"\buarters\b", "quarters"),
        (r"\buarter\b", "quarter"),
        (r"\bdddon[’']t\b", r"don’t"),
        (r"\b(don[’']t|we|We|you|to|can|would|not)\s+thin\b", r"\1 think"),
        (r"\b([A-Za-z]+)skyou\b", r"\1s you"),
        (r"\b([A-Za-z]+)kyou\b", r"\1 you"),
        (r"\bvi\s+va\b", "viśva"),
        (r"\bVi\s+va\b", "Viśva"),
        (r"\bthin(?=\s+(?:of|about|that|I|‘|\"))", "think"),
        (r"\bthin(?=\s*$)", "think"),
        (r"(?<![A-Za-zāīūṛṝḷḹṅñṭḍṇśṣḥĀĪŪṚṜḶḸṄÑṬḌṆŚṢḤ])admanābha(?![A-Za-zāīūṛṝḷḹṅñṭḍṇśṣḥĀĪŪṚṜḶḸṄÑṬḌṆŚṢḤ])", "Padmanābha"),
    ]
    for pattern, replacement in regex_replacements:
        text = re.sub(pattern, replacement, text)
    post_replacements = {
        "MMuktānām": "Muktānām",
        "PPadmanābha": "Padmanābha",
        "pPadmanābha": "padmanābha",
        "kkkartā": "kartā",
        "kkartā": "kartā",
        "unlesskyou": "unless you",
        "routeskyou": "routes you",
    }
    for old, new in post_replacements.items():
        text = text.replace(old, new)
    final_regex_replacements = [
        (r"\bP+Paramātmā\b", "Paramātmā"),
        (r"\bP+Pūtātmā\b", "Pūtātmā"),
        (r"\bk+karma\b", "karma"),
        (r"\bĪś(?:Īś)+vara-arpana\b", "Īśvara-arpana"),
        (r"\bvara\s+ārādhana\b", "Īśvara-ārādhana"),
        (r"\bś+śrutis\b", "śrutis"),
        (r"\bś+śraddhā+\b", "śraddhā"),
        (r"\bhowkit\b", "how it"),
        (r"\bInspite\b", "In spite"),
        (r"\binspite\b", "in spite"),
        (r"\bAtka\b", "At a"),
        (r"\batka\b", "at a"),
        (r"\bhanavān\b", "Dhanavān"),
        (r"\bratāpana\b", "Pratāpana"),
        (r"\bMi+Milky\b", "Milky"),
        (r"\bmiMilky\b", "milky"),
        (r"\bmi+milky\b", "milky"),
        (r"\bFacebookk\b", "Facebook"),
        (r"\bfacebookk\b", "Facebook"),
        (r"\bq+qualified\b", "qualified"),
        (r"\bk+knowingly\b", "knowingly"),
        (r"\bunk+knowingly\b", "unknowingly"),
        (r"\bD+uring\b", "During"),
        (r"\bd+during\b", "during"),
        (r"\buring\b", "during"),
        (r"\bdoeskyour\b", "does your"),
        (r"\bujya Swamiji\b", "Pujya Swamiji"),
        (r"\bD+Daśaratha\b", "Daśaratha"),
        (r"\bD+Dhaneśvara\b", "Dhaneśvara"),
        (r"\bD+Devahūti\b", "Devahūti"),
        (r"\bbabacked\b", "backed"),
        (r"\bFaceboo\b(?!k)", "Facebook"),
        (r"\bFacebookk+\b", "Facebook"),
        (r"\bma\s+ingPātala\b", "making Pātāla"),
        (r"\bq+quiet\b", "quiet"),
        (r"\blky way\b", "Milky Way"),
        (r"\bnowingness\b", "knowingness"),
        (r"\bLord eath\b", "Lord Death"),
        (r"\bformess\b", "formless"),
        (r"\bavai+(?:available)\b", "available"),
        (r"\bphilosoper\b", "philosopher"),
        (r"\bAxt\s*:", ""),
        (r"\brsis\b", "ṛṣis"),
        (r"\brsi\b", "ṛṣi"),
        (r"\bdoes not now\b", "does not know"),
        (r"\bŚa\s+ara\b", "Śaṅkara"),
        (r"\bPP+rahlāda\b", "Prahlāda"),
        (r"\bDD+evadutta\b", "Devadutta"),
        (r"\bdD+evadutta\b", "Devadutta"),
        (r"\bthekṣetra\b", "the kṣetra"),
        (r"\bisVāsudeva\b", "is Vāsudeva"),
        (r"\bVāsudevaas\b", "Vāsudeva as"),
        (r"\b([Pp])arigraha is collecting", r"\1arigraha is collecting"),
    ]
    for pattern, replacement in final_regex_replacements:
        text = re.sub(pattern, replacement, text)
    return text
